import Link from "next/link";
import { AdminStatus } from "@/components/admin/admin-status";
import { Container, Surface } from "@/components/ui";
import { getAdminCustomers } from "@/lib/admin/operations";

export const dynamic = "force-dynamic";

function value(input: string | string[] | undefined): string { return Array.isArray(input) ? input[0] ?? "" : input ?? ""; }
function pageValue(v: string): number { const n=Number.parseInt(v,10); return Number.isInteger(n)&&n>0?n:1; }
function href(search: string, page: number){const q=new URLSearchParams();if(search)q.set("search",search);q.set("page",String(page));return "/admin/customers?"+q.toString();}
function record(v: unknown): Record<string,unknown>{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};}
function moneyByCurrency(value: unknown){const r=record(value);const entries=Object.entries(r);return entries.length?entries.map(([c,a])=>c+" "+Number(a).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})).join(" · "):"—";}

export default async function AdminCustomersPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  const p=await searchParams;const search=value(p.search);const page=pageValue(value(p.page));
  const result=await getAdminCustomers({search,page,pageSize:20});
  return <section className="probee-section"><Container>
    <div className="max-w-4xl"><p className="probee-label">Customers</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-5xl">Customer management</h1><p className="mt-4 text-base leading-7 text-text-secondary">Staff-only customer support data from authenticated accounts, profiles, orders, reviews, and entitlements.</p></div>
    <Surface className="mt-8 p-4 sm:p-5"><form className="flex flex-col gap-3 sm:flex-row"><input name="search" defaultValue={search} placeholder="Email, display name or phone" className="min-h-11 flex-1 rounded-lg border border-[var(--probee-border-default)] bg-surface-2 px-3.5 text-sm text-text-primary"/><button className="probee-focus-ring min-h-11 rounded-lg bg-gold px-5 text-sm font-semibold text-text-inverse" type="submit">Search</button></form></Surface>
    <div className="mt-8 hidden overflow-x-auto rounded-xl border border-[var(--probee-border-subtle)] bg-surface-1 md:block"><table className="min-w-[1000px] w-full text-left text-sm"><thead className="border-b border-[var(--probee-border-subtle)] bg-surface-2 text-xs uppercase tracking-[0.08em] text-text-muted"><tr><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Phone</th><th className="px-4 py-3">Created</th><th className="px-4 py-3">Verified</th><th className="px-4 py-3">Orders</th><th className="px-4 py-3">Paid spend</th><th className="px-4 py-3">Reviews</th><th className="px-4 py-3">Entitlements</th><th className="px-4 py-3"></th></tr></thead><tbody>{result.items.map(item=>{const r=record(item);return <tr key={String(r.id)} className="border-b border-[var(--probee-border-subtle)] last:border-0"><td className="px-4 py-4"><Link href={"/admin/customers/"+String(r.id)} className="probee-focus-ring font-semibold text-gold">{String(r.email||"Customer")}</Link><p className="mt-1 text-xs text-text-muted">{String(r.displayName||"")}</p></td><td className="px-4 py-4">{String(r.phone||"—")}</td><td className="px-4 py-4 text-xs text-text-muted">{new Date(String(r.createdAt)).toLocaleString()}</td><td className="px-4 py-4"><AdminStatus label={r.emailVerifiedAt?"Verified":"Unverified"} tone={r.emailVerifiedAt?"success":"warning"}/></td><td className="px-4 py-4">{Number(r.orderCount||0)}</td><td className="px-4 py-4 text-gold">{moneyByCurrency(r.paidSpendByCurrency)}</td><td className="px-4 py-4">{Number(r.reviewCount||0)}</td><td className="px-4 py-4">{Number(r.entitlementCount||0)}</td><td className="px-4 py-4"><Link href={"/admin/customers/"+String(r.id)} className="probee-focus-ring inline-flex min-h-10 items-center rounded-lg border border-[var(--probee-border-default)] px-3 text-xs font-semibold">Open</Link></td></tr>})}</tbody></table></div>
    <div className="mt-6 grid gap-3 md:hidden">{result.items.map(item=>{const r=record(item);return <Surface key={String(r.id)} className="p-5"><Link href={"/admin/customers/"+String(r.id)} className="probee-focus-ring block"><p className="font-semibold text-gold">{String(r.email||"Customer")}</p><p className="mt-1 text-sm text-text-secondary">{String(r.displayName||"")}</p><p className="mt-2 text-xs text-text-muted">{String(r.phone||"No phone")}</p></Link><div className="mt-4 flex flex-wrap gap-2"><AdminStatus label={r.emailVerifiedAt?"Verified":"Unverified"} tone={r.emailVerifiedAt?"success":"warning"}/><AdminStatus label={Number(r.orderCount||0)+" orders"} /><AdminStatus label={Number(r.entitlementCount||0)+" entitlements"} /></div></Surface>})}</div>
    {result.items.length===0?<Surface className="mt-5 p-8 text-center"><p className="font-semibold">No customers found.</p><p className="mt-2 text-sm text-text-muted">The dashboard shows an empty state when no real customer accounts exist.</p></Surface>:null}
    {result.pageCount>1?<nav className="mt-6 flex flex-wrap items-center justify-between gap-3" aria-label="Customer pagination"><p className="text-sm text-text-muted">Page {result.page} of {result.pageCount}</p><div className="flex gap-2">{result.page>1?<Link href={href(search,result.page-1)} className="probee-focus-ring inline-flex min-h-10 items-center rounded-lg border border-[var(--probee-border-default)] px-3 text-sm font-semibold">Previous</Link>:null}{result.page<result.pageCount?<Link href={href(search,result.page+1)} className="probee-focus-ring inline-flex min-h-10 items-center rounded-lg border border-[var(--probee-border-default)] px-3 text-sm font-semibold">Next</Link>:null}</div></nav>:null}
  </Container></section>;
}
